apiVersion: v1
kind: Service
metadata:
  name: basic-python-app-service
  labels:
      app: basic-app
spec:
  selector:
    app: basic-app
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      nodePort: 30001
